#! /usr/bin/env bash
#
# /usr/local/sbin/firewall
#
# start/stop the firewall
#
# Pour que ce firewall s'active au démarrage de la passerelle
# Ajoutez les deux dernières lignes ci-dessous dans le fichier :
# -- /etc/network/interfaces
#
# auto enp0s8
# iface enp0s8 inet static
#       address 10.0.0.254
#       netmask 255.255.255.0
#       pre-up /usr/local/sbin/firewall start
#       post-down /usr/local/sbin/firewall stop
#
# --
#

error(){
	>&2 printf "Error: %s\n" "$1"
	[ -z "$2" ] || exit "$2"
}

[ -x /sbin/iptables ] || error "Commande « iptables » introuvable." 1

case "$1" in

	clean)
		iptables -F
		iptables -t nat -F
		iptables -X
	;;

	start)
		printf "Starting firewall: iptables"
		sh "$0" clean

		# Par défaut, ignore tout les paquets
		iptables -P INPUT DROP

		# Laisse passé les paquets qui ont déjà établie une poignée de main tcp
		iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

		# Tout le trafic loopback est accepté (127.0.0.1)
		iptables -A INPUT -i lo -j ACCEPT

		# Ouverture des ports désiré
		#iptables -A INPUT -p tcp --dport www -j ACCEPT
		iptables -A INPUT -p tcp --dport ssh -j ACCEPT
		#iptables -A INPUT -p tcp --dport smtp -j ACCEPT
		#iptables -A INPUT -p tcp --dport imaps -j ACCEPT
		#iptables -A INPUT -p tcp --dport https -j ACCEPT
		#iptables -A INPUT -p tcp --dport 8080 -j ACCEPT

		# Port rejeté
		iptables -A INPUT -p tcp --dport 113 -j REJECT

		# Gestion sécurisé des pings
		iptables -A INPUT -p icmp --icmp-type echo-reply -j ACCEPT
		iptables -A INPUT -p icmp --icmp-type destination-unreachable -j ACCEPT
		iptables -A INPUT -p icmp --icmp-type source-quench -j ACCEPT
		iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
		iptables -A INPUT -p icmp --icmp-type time-exceeded -j ACCEPT

		# Mise en place de la translation d'adresse pour les réseaux derrière la passerelle
		iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE

		printf ".\n"
	;;

	stop)
		printf "Stopping firewall: iptables"
		sh "$0" clean
		iptables -P INPUT ACCEPT
		printf ".\n"
	;;

	restart|reload|force-reload)
		printf "Restarting firewall: iptables"
		sh "$0" stop
		sh "$0" start
		printf ".\n"
	;;

	*)
		echo "Usage: $(basename "$0") start|stop|restart"
		exit 1
	;;
esac

exit 0

